!topic: 1234

!command: 800 disk driver
!dos-cmd: 800
Floppy disk driver for capacity
^Bincreasing. ^NUses special keys for
formatting with DOS command ^Uformat

!topic: util
Formatting, tape backup and restore,
disk procedures ^R& so on

!command: form 360
!dos-cmd: format a: /t:40/n:9
formats a diskette with capacity ^U360K

!command: form 400
!dos-cmd: format a: /t:40/n:10
formats a diskette with capacity ^U400K

!command: form 720
!dos-cmd: format a:/t:80/n:9
formats diskette with capacity ^U720K

!command: form 800
!dos-cmd: format a:/T:80/n:10
formats diskette with capacity ^U800K

!command: form1_2M
!dos-cmd: format a:
Use this command to format diskette in
drive^B with capacity 1.2 M^U.
The other formats you can get after
the start of ^U800.com

