unit DEMOHELP;

interface

const

  hcAsciiTable           = 6;
  hcCalculator           = 4;
  hcCalendar             = 5;
  hcCancelBtn            = 26;
  hcFCChDirDBox          = 28;
  hcFile                 = 13;
  hcFOFileOpenDBox       = 22;
  hcFOFiles              = 24;
  hcFOName               = 23;
  hcFOOpenBtn            = 25;
  hcNoContext            = 0;
  hcOCColorsDBox         = 30;
  hcOColors              = 19;
  hcOMMouseDBox          = 29;
  hcOMouse               = 18;
  hcOpenBtn              = 27;
  hcOptions              = 17;
  hcORestoreDesktop      = 21;
  hcOSaveDesktop         = 20;
  hcPrevious             = 16;
  hcPuzzle               = 3;
  hcSAbout               = 8;
  hcSAsciiTable          = 11;
  hcSCalculator          = 12;
  hcSCalendar            = 10;
  hcShowClip             = 14;
  hcSPuzzle              = 9;
  hcSystem               = 7;
  hcViewer               = 2;
  hcWindows              = 15;

implementation

end.
