                                                     Little is beautiful


                     COMpact Soft presents ...

     
     Tiny utilities of  significant value.  Multi-purpose, but
not expensive to your  hard disk,  especially if you have none.
The size is always competitive to existing commercial software
in the same domain. All of them provided as shareware with a fee
not exceeding 10 roubles ( dollars, pounds, etc. ).

     Members :  Alexander Dudarenko
                Dmitry Kohmanyuk
                Igor Sviridov


at!.com           987  11/04/90  20:06 		AntiTurbo Utility 
at!.doc          2624  11/04/90  20:26 		
ewoff.com           6   6/04/90  23:19 		Event_Wait Off Utility 

ascii.com        1800   4/05/90  21:24 		ASCII Input Utility

zap.com          1254   5/05/90  23:31 		Directory trees removal

ega25.com           5  11/04/90  16:20 		EGA 25 lines text mode
ega43.com          10  11/04/90  16:24 		EGA 43 lines text mode

kbqui.com           6  11/04/90  20:23 		Keyboard Fastener Utility
kbqui.doc         318  10/04/90  22:29

nosound.com         7  11/04/90  16:39 		Sound Off Utility
sound.com          19  11/04/90  17:04 		Demo for NoSound

snake.com        1596  25/04/90  00:46 		The smallest game for EGA & AT

talker.com       3679   1/04/90  01:10		Shell Chatter

descript.ion      646   8/05/90  19:15		4DOS Directory Description

	Satisfaction guaranteed or your money back !!!

		Phones : (044) 2112173; (044) 2718856; (044) 2638770.
		FAX    : (044) 2902105
		Telex  : will be later
		EMAIL  : soon will be available; repairing

		Mail   : 252127, Kiev - 127, box # 804/7
                         Sviridov Igor Anatolievich

